### ISSUE TITLE
Captura parcial

### ISSUE THREAD

**Issue by sthales** [ipagdevs/ipag-sdk-php#2]
Como fazer uma captura parcial, assim como era possível no SDK antigo? 
https://github.com/jhernandes/ipag-sdk-php/releases/tag/v1.1.0

**Comment by jhernandes** [comment]
Boa tarde @sthales estaremos incluindo em breve essa funcionalidade.

**Comment by lcsLucas** [comment]
Olá @sthales, link de referência para captura parcial, https://github.com/ipagdevs/ipag-sdk-php#capturar-pagamento.
