### ISSUE TITLE
Não é possivel fazer o composer require do SDK

### ISSUE THREAD

**Issue by webflixtec** [ipagdevs/ipag-sdk-php#3]
![image (3)](https://github.com/ipagdevs/ipag-sdk-php/assets/154339257/fcd8a3ff-6a3c-45d9-ad71-8ade68c9b95a)

**Comment by jhernandes** [comment]
Boa tarde @webflixtec estamos resolvendo, poderia testar novamente?

**Comment by webflixtec** [comment]
Deu certo

Atenciosamente,


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/03/24,
10:34:30

Em seg., 4 de mar. de 2024 às 16:46, João Hernandes <
***@***.***> escreveu:

**Comment by jhernandes** [comment]
Que bom! @webflixtec precisando de alguma ajuda, nossa equipe está disponível através do contato: suporte@ipag.com.br.
