### ISSUE TITLE
Erro de dependencia psr/log ^1.1

### ISSUE THREAD

**Issue by webflixtec** [ipagdevs/ipag-sdk-php#5]
ipagdevs/ipag-sdk-php[v0.1.0, v1.0.0, ..., v1.2.0] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but these were not loaded, likely because it conflicts with another require.

vocês estão utilizando uma versão muito antiga de psr/log

é possivel atualizar?

![image](https://github.com/ipagdevs/ipag-sdk-php/assets/154339257/dc90894e-df97-4576-8518-94b4b166d59f)

**Comment by Kubinyete** [comment]
Bom dia @webflixtec !

Nós até avaliamos a possibilidade de dar upgrade no seguinte pacote, porém, de acordo com as informações do `psr/log` ele está exigindo a versão do PHP 8.0 ou superior.

Isso acaba quebrando nossa compatibilidade existente com as versões do 7.0 e superior, para não afetar uma base de usuários maior, decidimos internamente por manter essa compatibilidade.

Caso queira, sugiro realizar o fork do projeto ou avaliar se é possível efetuar o downgrade em seu próprio projeto para resolver os requerimentos de dependência do Composer.

Fico a disposição caso necessitem de algo à mais.

**Comment by webflixtec** [comment]
Ok eu fiz isso

Se quiserem podem lançar uma versão nova especificando a compatibilidade
acima do PHP 8 exemplo v2.X.X

Não trabalho mais com a versão 7 do PHP pois ficou obsoleta.

Atenciosamente,


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/04/24,
12:11:15

Em ter., 9 de abr. de 2024 às 11:19, Vitor Kubinyete <
***@***.***> escreveu:
